jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'  # 也可以用 'windows-latest'
  steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.9'  # 这里可以选择 JDK 版本
      mavenVersionOption: 'Default'
