trigger:
  branches:
    include:
      - master

pool:
  name: demofeng
  demands:
    - Agent.Name -equals localhost

jobs:
- job: TestJob
  displayName: '测试自建 Agent 的流水线'
  steps:
  - script: |
      echo "Hello, this is my self-hosted agent running the pipeline!"
      echo "当前时间: $(date)"
    displayName: '执行测试脚本'
